#!/usr/bin/env bash

[ -d "/tmp/.pbash_utils" ] || git clone https://github.com/parveenchahal/pbash_utils.git /tmp/.pbash_utils
pushd /tmp/.pbash_utils > /dev/null
git pull
chmod +x ./install.sh
./install.sh --install all
popd > /dev/null
