#!/usr/bin/env bash

function error_echo() {
  echo -e "\e[01;31m${@}\e[0m"
}

source pbash-args.sh || { echo "pbash-args.sh is not installed"; exit 1; }

pbash.args.extract -l name: -o name -- "$@"

[ "$name" == "" ] && { error_echo "--name is required argument."; exit 1; }

installation_path="$HOME/.local/bin/"
[ -d $HOME/.local/bin ] || { error_echo "Uninstallation failed"; exit 1; }

p="${installation_path}${name}"

[ -f "$p" ] && echo "Uninstalling: $name" && rm "$p" || { error_echo "Uninstallation failed"; exit 1; }