#!/usr/bin/env bash

kv="$1"

key="${kv%=*}"
value="${kv#*=}"

pinstall --name "$key" --content "#!/usr/bin/env bash
$value \"\$@\"
"

# echo "#!/usr/bin/env bash" > /tmp/$key
# printf "$value \"\$@\"" >> /tmp/$key
# pinstall --file /tmp/$key