#!/usr/bin/env bash

source pbash-args.sh

file=()
pbash.args.extract -s 'f:' -l 'file:' -o file -- "$@" || { read -p "-f|--file (file path): "; file=$REPLY; }

inform=()
pbash.args.extract -l 'inform:' -o inform -- "$@" || { read -p "--inform (der/pem): "; inform=$REPLY; }

outfile=()
pbash.args.extract -s 'o:' -l 'outfile:' -o outfile -- "$@" || { read -p "-o|--outfile (file path): "; outfile=$REPLY; }

x=$(openssl asn1parse -inform $inform -in "$file" | tail -n 1 | cut -d ":" -f 1 | xargs)

peval -v -- openssl asn1parse -inform "$inform" -in "$file" -out "$outfile" -strparse "$x" -noout
