#!/usr/bin/env bash

source pbash-args.sh || { echo "pbash-args.sh is not installed"; exit 1; }

file=()
pbash.args.extract -s 'f:' -l 'file:' -o file -- "$@" || { read -p "-f|--file (file path): "; file=$REPLY; }

inform=()
pbash.args.extract -l 'inform:' -o inform -- "$@" || { read -p "--inform (der/pem): "; inform=$REPLY; }

outfile=()
pbash.args.extract -s 'o:' -l 'outfile:' -o outfile -- "$@" || { read -p "-o|--outfile (file path): "; outfile=$REPLY; }

outform=()
pbash.args.extract -l 'outform:' -o outform -- "$@" || { read -p "--outform (der/pem): "; outform=$REPLY; }

peval -v -- openssl x509 -pubkey -inform "$inform" -in "$file" -outform "$outform" -out "$outfile" -noout
